### ISSUE TITLE
"GroupPolicy Permissions" error

### ISSUE THREAD

**Issue by neztach** [EvotecIT/GPOZaurr#5]
under the "Warnings & Error Section" can the errors adjust to be more user friendly?  Unclear why these are problems.  Looked up a good chunk of user/group SID's found and could locate them.

.EXAMPLE
  .COMMENT USED
    Cannot convert value "S-1-5-18" to type "System.Guid". Error: "Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)."
.SUGGESTION
  .REFERENCE
    According to: https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/security-identifiers-in-windows
    "S-1-5-18" = Name: Local System | Description: A service account that is used by the operating system.
  .ALTERNATIVE ERROR COMMENT
    Contains value of a 'Local System Account'

.EXAMPLE
  .COMMENT USED
    Cannot convert value "S-1-5-XX-XXXXXXXXXX-XXXXXXXXXX-XXXXXXXXXX-XXXX" to type "System.Guid". Error: "Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)."
.ALTERNATE POST-PROCESSING
    ### I'm sure you can make this more elegant
    $sids = @("S-1-5-21-0123456789-0123456789-0123456789-1108")

    $UserGroupPattern = [Regex]::new('/^S-1-[0-59]-\d{2}-\d{8,10}-\d{8,10}-\d{8,10}-\d[1-6]/')
    Foreach ($sid in $sids){
        If ($UserGroupPattern.Matches($sid)){
            Get-ADObject –IncludeDeletedObjects -Filter "objectSid -eq '$sid'" | Select-Object name, objectClass
        } else {
            "not a User or Group SID"
        }
    }
  .ALTERNATE ERROR COMMENT
    SID is a user or group

and TargetName is empty, so while the errors are undoubtedly accurate, they don't specify to which GPO they are referring, or why they are errors exactly.

**Comment by PrzemyslawKlys** [comment]
My module catches 90% of errors by design and converts them to Warnings. Those errors about system.guids are because it tries multiple ways to get a proper ID and when one way gives an error it tries another one. So you don't really see those "errors" as those are already processed and a warning is only given if it really can't do anything with it. 

So in other words if you run Invoke-GPOZaurr or anything other manually you won't see anything other than Warnings, and only if that means something. Surely not for the GUID should contain 32digits. 

However, the idea was that if you run those cmdlets via Task Scheduler any errors and warnings would be swallowed and you won't see them.

So I implemented a system where it catches all warnings and all errors:

https://github.com/EvotecIT/GPOZaurr/blob/8817bda408938020c82dd5b5be87de5c0f7682ef/Public/Invoke-GPOZaurr.ps1#L104-L134

and saves them to variables and then displays in GUI. The problem is that it's catching both Warning and Error for the same thing. 

For example, if I do

```powershell
try {
   doSomething
} catch {
   Write-Warning 'Something happened, but it's ok"
}
```

it would display both warning and errors at the same time, where I only want warnings. I would actually want only errors that happen that I've not caught with try/catch but so far I have not been able to do so.

In new version I think I planned to add parameters -HideErrors, -HideWarnings to prevent that, but the problem is a lot of people will be wondering - just like you are about it. So I might as well disable it by default and enable it on request.

**Comment by neztach** [comment]
I appreciate all the great work you do!

I found this link. I don't know that it'll bestow any knowledge you don't already have, but it might give you a different perspective on how to handle warnings/errors:

https://stackoverflow.com/questions/47376768/capturing-powershell-warning

**Comment by PrzemyslawKlys** [comment]
That's what I am using. Catching both streams. Warning and Errors stream. The problem is, it also displays Errors stream even tho it was already handled with a warning.
